# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  jwt_secret: 4bbbe48f6c2648582112d180222397eba6b8c59075988e206d281a019fc39258890a3a57e99d9abcdd74e9344e364a0d4163b7e7aea3f954bde4ae53a52f247e
  secret_key_base: 316c176bc25dc01a1c7df2030f67709765e4e522b833b5fa372adc5db122dc0daf78d726ea783697dbe046a0ebf49b4f87faf15c8c5c33bb11df924c469ab6c6

test:
  jwt_secret: 21150f759465bbaefc886db6afa32cfb08cb311bdcdd2a4022a822639a8bff3efed3e390cc1b6f9c6961eaa5661853c52b1df0516abc0be68bd654a4a927e2ad
  secret_key_base: 95050cbde34b20e93bb275c68208fd29dc59c0530b27d603ae5db2621378b78d18d35d72af821d03584d6f732624369d1d5582bf414d9d123041e1b9f7693d3e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  jwt_secret: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
